- name: creating catalouge
  hosts: catalogue
  become: yes
  tasks:
  - name: Run nodejs script
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: installing nodejs
    ansible.builtin.yum:
     name: nodejs
     state: present
  - name: checking user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: Add the user 'roboshop' after validating
    when: out.rc == 1
    ansible.builtin.user:
     name: roboshop  
  - name: checking app directory
    ansible.builtin.stat:
     path: /app
    register: directory
  - name: Create a directory app
    when: 'directory.stat.exits' == false
    ansible.builtin.file:
     path: app
     state: directory     
  - name: extract catalogue.zip
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /tmp
     remote_src: yes      
  
          
 




