- name: creating catalouge
  hosts: catalogue
  become: yes
  tasks:
  - name: Run nodejs script
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: installing nodejs
    ansible.builtin.yum:
     name: nodejs
     state: present
  - name: checking user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: Add the user 'roboshop' after validating
    when: out.rc == 1
    ansible.builtin.user:
     name: roboshop  
  - name: checking app directory
    ansible.builtin.stat:
     path: /app
    register: directory
  - name: Create a directory app
    when: directory.stat.exists == False
    ansible.builtin.file:
     path: /app
     state: directory 
  - name: Download catalogue.zip
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
     dest: /tmp 
  - name: change directory
    ansible.builtin.command: cd /app         
  - name: extract catalogue.zip
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /tmp
     remote_src: yes   
  - name: download npm
    ansible.builtin.command: npm install 
    args:
     chdir: /app
  - name: Reload catalogue
    ansible.builtin.systemd:
     daemon_reload: true  
  - name: Start service catalogue and enable
    ansible.builtin.service:
     name: catalogue
     state: started
     enabled: yes  
  - name: Copying mongo.repo
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo   
  - name: installing mongo-org-shell
    ansible.builtin.yum:
     name: mongodb-org-shell
     state: present   
  - name: loading schema
    ansible.builtin.command: mongo --host 18.234.29.95 < /app/schema/catalogue.js    


  
          
 




