- name: creating dispatching
  hosts: dispatch
  become: yes
  tasks:
  - name: installing golang
    ansible.builtin.yum:
     name: golang
     state: present
  - name: checking user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: validating and creating user
    when: out.rc == 1
    ansible.builtin.user:
     name: roboshop  
  - name: checking app directory
    ansible.builtin.stat:
     path: /app
    register: directory  
  - name: Create a directory app
    when: directory.stat.exists == False
    ansible.builtin.file:
     path: /app
     state: directory   
  - name: Download
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
     dest: /tmp
  - name: extract dispatch
    ansible.builtin.unarchive:
     src: /tmp/dispatch.zip
     dest: /app
     remote_src: yes 
  - name: download dependencies1
    ansible.builtin.command: go mod init 
    ignore_errors: true
  - name: download dependencies2
    ansible.builtin.command: go get 
    ignore_errors: true 
  - name: download dependencies3
    ansible.builtin.command: go build 
    ignore_errors: true
  - name: Copy dispatch service
    ansible.builtin.copy:
     src: dispatch.service
     dest: /etc/systemd/system/dispatch.service      
  - name: Reload dispatch
    ansible.builtin.systemd:
     daemon_reload: true  
  - name: Start dispatch and enable
    ansible.builtin.service:
     name: user
     state: started
     enabled: true       
      


   