- name: creating shipping
  hosts: shipping
  become: yes
  tasks:
  - name: installing maven
    ansible.builtin.yum:
     name: maven
     state: present 
  - name: checking user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: validating and creating user
    when: out.rc == 1
    ansible.builtin.user:
     name: roboshop  
  - name: checking app directory
    ansible.builtin.stat:
     path: /app
    register: directory
  - name: Create a directory app
    when: directory.stat.exists == False
    ansible.builtin.file:
     path: /app
     state: directory 
  - name: Download
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
     dest: /tmp
  - name: extract shipping.zip
    ansible.builtin.unarchive:
     src: /tmp/shipping.zip
     dest: /app
     remote_src: yes    
  - name: mvn clean package
    ansible.builtin.command: mvn clean package
    args:
     chdir: /app
  - name: changing names
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
     chdir: /app
        