- name: creating user\
  hosts: user
  become: yes
  tasks:
  - name: download rpm repo
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: install nodejs
    ansible.builtin.yum:
     name: nodejs
     state: present
  - name: checking user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: validating and creating user
    when: out.rc == 1
    ansible.builtin.user:
     name: roboshop  
  - name: checking app directory
    ansible.builtin.stat:
     path: /app
    register: directory
  - name: Create a directory app
    when: directory.stat.exists == False
    ansible.builtin.file:
     path: /app
     state: directory 
  - name: Download
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/user.zip
     dest: /tmp
  - name: extract user
    ansible.builtin.unarchive:
     src: /tmp/user.zip
     dest: /app
     remote_src: yes       
  - name: npm install
    ansible.builtin.command: npm install
    args:
     chdir: /app   
  - name: Copy user service
    ansible.builtin.copy:
     src: user.service
     dest: /etc/systemd/system/user.service 
  
  - name: Copy user service
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo
  - name: Reload user
    ansible.builtin.systemd:
     daemon_reload: true  
  - name: installing mongo-org-shell
    ansible.builtin.yum:
     name: mongodb-org-shell
     state: present        
  - name: load schema
    ansible.builtin.shell: mongo --host 54.89.215.34 < /app/schema/user.js           
  - name: Start user catalogue and enable
    ansible.builtin.service:
     name: user
     state: started
     enabled: true       
      


