- name: creating web
  hosts: web
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.yum:
     name: nginx
     state: present
  - name: Start service nginx and enable
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes